### ISSUE TITLE
azure vm image list doesn't work

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-xplat-cli#2385]
```
$ azure vm image list westus canonical

info:    Executing command vm image list
info:    The parameters --offer and --sku if specified will be ignored
+ Getting virtual machine image offers (Publisher: "canonical" Location:"westus")
error:   The value of parameter 'version' is invalid.
info:    Error information has been recorded to /home/cole/.azure/azure.err
error:   vm image list command failed
```

**Comment by colemickens** [comment]
`azure vm list westus canonical ubuntuserver` works, but I don't understand why. The failure above indicates that it needs "version", but I'm passing in the offer in this case.

We should also consider publising this list of ImageURNs somewhere, or making the API that this queries available.

**Comment by huangpf** [comment]
The ```ubuntuserver``` is OK, but the following offer has problem: ```azure vm image list westus canonical Ubuntu15.04Snappy```. 

And the error occurs when the command gets the version ```15.04.201508290653``` from the sku, but fails to make a further call to get the details. The same error can be seen from calling:
```
azure vm image list westus canonical Ubuntu15.04Snappy 15.04-Snappy -vv
```

```
silly:   requestOptions
silly:   {
silly:       rawResponse: false,
silly:       queryString: {},
silly:       method: 'GET',
silly:       headers: { Content-Type: 'application/json' },
silly:       url: 'https://management.azure.com/subscriptions/xxx-xxx-xxx-xxx/providers/Microsoft.Compute/locations/westus/p
ublishers/canonical/artifacttypes/vmimage/offers/Ubuntu15.04Snappy/skus/15.04-Snappy/versions/15.04.201511272055?api-version=2015-06-15'
silly:   }
silly:   returnObject
silly:   {
silly:       statusCode: 400,
silly:       body: "{\015\n  "error": {\015\n    "code": "InvalidParameter",\015\n    "target": "version",\015\n    "message": "The value of para
meter 'version' is invalid."\015\n  }\015\n}"
silly:   }
error:   The value of parameter 'version' is invalid.
```

**Comment by colemickens** [comment]
It seems to me that the first example I posted, `azure vm image list westus canonical` should also work, but doesn't.

**Comment by colemickens** [comment]
If this is how users are expected to discover images (since we don't seem to publish a list anywhere) then specifying any level of the imageurn should result in a list of results.

I should get a ton of results from `azure vm image list westus` and I should get a small subset of results when I specify everything except the version.

As it stands now, I have to ... basically guess... that "canonical" is a provider, and then that "ubuntuserver" is the offer name... that's really not good for a user who is using `azure vm list` because they *don't know* that information already.

For some context, I just wanted to spin up a VM quickly and I wound up wasting an inordinate amount of time just trying to figure out the ImageURN for the latest ubuntu release. Needless friction IMO.

**Comment by huangpf** [comment]
You can use the following commands to list ```publisher```, ```offer```, and ```sku``` names, in that order.

```
vm image list-publishers [options] <location>
vm image list-offers [options] <location> <publisher>
vm image list-skus [options] <location> <publisher> <offer>
```

The command ```vm image list``` requires ```publisher``` (along with ```location```) input, because there are too many calls to get all the publishers, and it would impact the command's running time significantly.

**Comment by colemickens** [comment]
That's great. Thank you!

**Comment by huangpf** [comment]
```azure vm image list westus canonical``` doesn't work because of the same reason that the publisher publishes a version string that would fail the later call to get the particular version image. This is a problem that the service team needs to address, or we probably need to make the query command more robust regarding exception cases.

```azure vm image list westus MicrosoftWindowsServer``` or ```azure vm image list westus SUSE``` would work fine.

**Comment by colemickens** [comment]
Thank you for this detailed information.

Does that mean that the PS version is affected similarly?

**Comment by huangpf** [comment]
No problem. Hope it helps.

The PS counterpart ```Get-AzureVMImage``` is different in that its 1st parameter set requires all parameters of location, publisher, offer, and sku, but it doesn't make the further call to verify the image in particular versions. Its 2nd parameter set takes an additional version input to get the particular image.

```
PS C:\> Get-AzureVMImage -Location westus -PublisherName canonical -Offer Ubuntu15.04Snappy -Skus 15.04-Snappy

Version            FilterExpression Skus         Offer             PublisherName Location Id
-------            ---------------- ----         -----             ------------- -------- --
15.04.201508290653                  15.04-Snappy Ubuntu15.04Snappy canonical     westus   /Subscriptions/...
15.04.201509241855                  15.04-Snappy Ubuntu15.04Snappy canonical     westus   /Subscriptions/...
...
```

The problem of not being able to query the details of the image can be reproduced by:
```
PS C:\> Get-AzureVMImage -Location westus -PublisherName canonical -Offer Ubuntu15.04Snappy -Skus 15.04-Snappy -Version 15.04.201508290653
Get-AzureVMImage : InvalidParameter: The value of parameter 'version' is invalid.
OperationID : 'c284ac2a-50af-408d-9ff8-12a86c67f6f7'
At line:1 char:1
+ Get-AzureVMImage -Location westus -PublisherName canonical -Offer Ubu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureVMImage], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMImageCommand
```

**Comment by colemickens** [comment]
I see.

In this case, my main concern was addressed (discover-ability via list-{publishers,offers,skus}).

We can go ahead and close this unless you want to keep it open to correlate with any internal bug for the version-detail-query server side issue mentioned.

**Comment by huangpf** [comment]
You're welcome. Let's keep it open to track the aforementioned issue, and try to get a fix by next sprint. Thanks.

**Comment by ahmetalpbalkan** [comment]
+1 I'm seeing the same error.

**Comment by ahmetalpbalkan** [comment]
@huangpf any ideas how this passed the test runs in the first place?

**Comment by huangpf** [comment]
@ahmetalpbalkan 
It's very likely because at that time there is no problematic version in the published images. This actually is also a service issue in that it lists certain versions of images, but the get operation on them will fail.

**Comment by ahmetalpbalkan** [comment]
@huangpf oh I now see the root cause of this issue. Thanks.

**Comment by huangpf** [comment]
This issue should have been fixed. Close for now.

**Comment by carbontwelve** [comment]
When I issue the command `azure vm image list -p canonical` it asks me to confirm the location so I enter `North Europe` and it provides me with the following error:

```
C:\Users\Simon Dann>azure vm image list -p canonical
info:    Executing command vm image list
Location: North Europe
info:    The parameters --offer and --sku if specified will be ignored
+ Getting virtual machine image offers (Publisher: "canonical" Location:"northeurope")
error:   The value of parameter 'version' is invalid.
info:    Error information has been recorded to C:\Users\Simon Dann\.azure\azure.err
error:   vm image list command failed
```

I get the same error if I execute the command `azure vm image list "North Europe" "canonical"`

**Comment by huangpf** [comment]
@carbontwelve May I know which version did you use? ```0.9.14``` shall have the fix.

**Comment by lmazuel** [comment]
Hello,

I was having the same issue. The `list` now works
```
# azure --version
0.9.14 (node: 0.10.25)
# azure vm image list westus canonical ubuntu15.04snappy 15.04-Snappy 15.04.201508290653
info:    Executing command vm image list
+ Getting virtual machine images (Publisher:"canonical" Offer:"ubuntu15.04snappy" Sku: "15.04-Snappy" Location:"westus")
data:    Publisher  Offer              Sku           OS         Version             Location  Urn
data:    ---------  -----------------  ------------  ---------  ------------------  --------  -----------------------------------------------------------
data:    canonical  ubuntu15.04snappy  15.04-Snappy  undefined  15.04.201508290653  westus    canonical:ubuntu15.04snappy:15.04-Snappy:15.04.201508290653
data:    canonical  ubuntu15.04snappy  15.04-Snappy  undefined  15.04.201509241855  westus    canonical:ubuntu15.04snappy:15.04-Snappy:15.04.201509241855
info:    vm image list command OK
```

But not the `show`

```
# azure vm image show westus canonical ubuntu15.04snappy 15.04-Snappy 15.04.201508290653
info:    Executing command vm image show
error:   The value of parameter 'version' is invalid.
info:    Error information has been recorded to /root/.azure/azure.err
error:   vm image show command failed
```

By adding the `-vv` we still see the REST API error to the details request.

Actually, I was working with REST API directly, got an error, and Google brought me here. Do you know if there is a bug report somewhere regarding the REST API directly? It's maybe the best way to fix this.

Thank you!

**Comment by ahmetalpbalkan** [comment]
@lmazuel 

```
$ azure vm image show westus canonical ubuntu15.04snappy 15.04-Snappy 15.04.201508290653
error:   'show' is not an azure command. See 'azure help'.
```
?

**Comment by huangpf** [comment]
@lmazuel 
I also noticed this problem, but it's different from the original post here. Could you please file another issue for it?

The cause is on the service side in that some of the images shown by the ```list``` operation can't be queried using the ```get`` operation. The ```-vv``` option will show the details.

Since this is a service API issue, you can contact Azure support for your subscription and raise the issue. Thanks.
